// Imports
var ___CSS_LOADER_API_IMPORT___ = __webpack_require__(23645);
exports = ___CSS_LOADER_API_IMPORT___(false);
// Module
exports.push([module.id, ".mod_tips_songlist {\n    position: absolute;\n    top: 400px;\n    left: 10px;\n    width: 350px;\n    box-shadow: 0 0 25px rgba(0,0,0,.1);\n    line-height: 22px;\n    z-index: 999;\n    background-color: #fff;\n    color: rgba(0,0,0,.9);\n    border-radius: 8px\n}\n\n.mod_tips_songlist::before {\n    content: '';\n    position: absolute;\n    left: 0;\n    top: 0;\n    right: 0;\n    bottom: 0;\n    border-radius: 8px;\n    background-color: rgba(255,255,255,.1)\n}\n\n.mod_tips_songlist .tag_exclusive,.mod_tips_songlist .tag_mv,.mod_tips_songlist .tag_new {\n    display: inline-block;\n    vertical-align: -4px;\n    margin-left: 4px;\n    margin-right: 0\n}\n\n.mod_tips_songlist .tips_songlist_icon :first-child {\n    margin-left: 20px\n}\n\n.tips_songlist__inner {\n    position: relative\n}\n\n.tips_songlist__hd {\n    padding: 13px 20px 10px\n}\n\n.tips_songlist__song {\n    display: -webkit-box\n}\n\n.tips_songlist__tit {\n    font-weight: 400;\n    font-size: 13px;\n    line-height: 20px;\n    margin-bottom: 4px;\n    text-align: justify;\n    -webkit-box-flex: 1\n}\n\n.tips_songlist__desc {\n    text-align: justify;\n    line-height: 20px;\n    font-size: 12px\n}\n\n.tips_songlist_detail {\n    padding: 10px 20px 9px;\n    font-size: 12px\n}\n\n.tips_songlist_detail::after {\n    content: \"\";\n    display: block;\n    clear: both\n}\n\n.tips_songlist_detail__list {\n    display: -webkit-box;\n    -webkit-box-align: center\n}\n\n.tips_songlist_icon {\n    font-size: 0\n}\n\n.mod_hover_tips {\n    position: 'absolute';\n    max-width: 350px;\n    line-height: 22px;\n    padding: 10px 13px;\n    box-shadow: 1px 1px 12px 0 rgba(0,0,0,.15);\n    background-color: #fff;\n    border-radius: 4px\n}\n\n.mod_hover_tips::before {\n    content: '';\n    position: absolute;\n    left: 0;\n    top: 0;\n    right: 0;\n    bottom: 0;\n    border-radius: 8px;\n    background-color: rgba(255,255,255,.1)\n}\n\n.hover_tips__inner {\n    position: relative\n}", ""]);
// Exports
module.exports = exports;


//# sourceURL=webpack://qqmusic/./src/lib/css/popup.css?./node_modules/css-loader/dist/cjs.js