// Imports
var ___CSS_LOADER_API_IMPORT___ = __webpack_require__(23645);
exports = ___CSS_LOADER_API_IMPORT___(false);
// Module
exports.push([module.id, ".cover_layout {\n  position: absolute;\n  width: 100%;\n  height: 100%;\n  z-index: 1000;\n  background-color: black;\n  transform: translateY(100%);\n  transition: transform 0.5s;\n  display: flex;\n  flex-direction: column;\n}\n.cover_layout.cover_layout--show {\n  transform: translateY(0px);\n}\n.cover_layout .cover_layout_blur,\n.cover_layout .cover_layout_shadow {\n  position: absolute;\n  width: 120%;\n  height: 120%;\n}\n.cover_layout .cover_layout_blur {\n  border: none;\n  background: no-repeat center / 100% url('https://y.gtimg.cn/music/photo_new/T002R300x300M000004AhJHV3slLjN_1.jpg?max_age=2592000');\n  filter: blur(30px);\n  z-index: -1;\n  left: -10%;\n  right: -10%;\n}\n.cover_layout .cover_layout_shadow {\n  background-color: black;\n  filter: opacity(0.4);\n  z-index: -1;\n}\n.cover_layout .cover_player_page_top_cont_cover {\n  height: 80px;\n  display: flex;\n  flex-direction: row;\n  align-items: center;\n  z-index: 1000;\n  background-color: transparent;\n  -webkit-app-region: drag;\n  justify-content: space-between;\n  padding: 0 40px;\n}\n.cover_layout .cover_player_page_top_cont_cover .cover_player_page_top_cont {\n  -webkit-app-region: no-drag;\n  width: auto;\n}\n.cover_layout .cover_player_page_top_cont_cover .cover_player_page_top_cont.left {\n  display: block;\n  background: transparent;\n}\n.cover_layout .cover_player_page_top_cont_cover .cover_player_page_top_cont.right {\n  display: flex;\n  align-items: center;\n}\n.cover_layout .cover_player_page_main_cont {\n  flex: 1;\n  display: flex;\n  align-items: center;\n  justify-content: space-around;\n  flex-wrap: nowrap;\n  padding: 0 70px;\n  overflow: hidden;\n  margin-bottom: 40px;\n}\n.cover_layout .cover_player_page_main_cont .cover_album__wrapper {\n  flex: 1;\n  min-width: 350px;\n  min-height: 350px;\n  padding: 8%;\n}\n.cover_layout .cover_player_page_main_cont .cover_album__wrapper .cover_album {\n  width: 100%;\n  height: 100%;\n  max-width: 500px;\n  max-height: 500px;\n}\n.cover_layout .cover_player {\n  height: 87px;\n  z-index: 100;\n}\n", ""]);
// Exports
module.exports = exports;


//# sourceURL=webpack://qqmusic/./src/pages/cover_player/css/index.less?./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js