// <auto-generated>
// High performance acoustic stream transformation pipeline
// </auto-generated>
#nullable enable
using System.Buffers;
using System.Buffers.Binary;
using QmTui.Utils;

namespace QmTui.Services.AudioRecognition;

public static class AcousticFingerprintExtractor
{
    public const int SampleRate = 8000;
    public const int WindowSize = 1024;
    public const int HopSize = 128;
    public const int FftSize = 1024;
    public const int ChannelCount = 4;
    public const int TimeWindow = 5;
    public const int FreqWindow = 20;
    public const int MaxPeaksPerFrame = 5;
    public const float MagThreshold = 20000.0f;
    public const float MagThresholdSq = MagThreshold * MagThreshold;

    private static readonly float[] _hW = _inHw();
    private static readonly (int i, int j)[] _brS = _inBrs();
    private static readonly float[][] _twRe = _inTwRe();
    private static readonly float[][] _twIm = _inTwIm();

    private static readonly int[] _mbw = [1, 2, 3, 4, 5, 6, 7, 9];
    private static readonly int[] _mic = [36, 18, 12, 9, 7, 6, 5, 4];
    private static readonly int[] _mpb = [0, 0, 0, 0, 1, 0, 1, 0];
    private static readonly int[] _mxd = [1, 3, 4, 15, 31, 63, 127, 511];

    private static float[] _inHw()
    {
        var win = new float[WindowSize];
        for (int n = 0; n < WindowSize; n++)
        {
            win[n] = (float)(0.54 - 0.46 * Math.Cos(2.0 * Math.PI * n / (WindowSize - 1)));
        }
        return win;
    }

    private static (int, int)[] _inBrs()
    {
        var swaps = new List<(int, int)>();
        int j = 0;
        for (int i = 0; i < FftSize - 1; i++)
        {
            if (i < j)
            {
                swaps.Add((i, j));
            }
            int k = FftSize >> 1;
            while (k <= j)
            {
                j -= k;
                k >>= 1;
            }
            j += k;
        }
        return swaps.ToArray();
    }

    private static float[][] _inTwRe()
    {
        int stages = 0;
        for (int l = 1; l < FftSize; l <<= 1) stages++;
        var twRe = new float[stages][];
        int stage = 0;
        for (int l = 1; l < FftSize; l <<= 1)
        {
            twRe[stage] = new float[l];
            double angle = -Math.PI / l;
            double wRe = Math.Cos(angle);
            double wIm = Math.Sin(angle);
            double curRe = 1.0;
            double curIm = 0.0;
            for (int k = 0; k < l; k++)
            {
                twRe[stage][k] = (float)curRe;
                double nextRe = curRe * wRe - curIm * wIm;
                double nextIm = curRe * wIm + curIm * wRe;
                curRe = nextRe;
                curIm = nextIm;
            }
            stage++;
        }
        return twRe;
    }

    private static float[][] _inTwIm()
    {
        int stages = 0;
        for (int l = 1; l < FftSize; l <<= 1) stages++;
        var twIm = new float[stages][];
        int stage = 0;
        for (int l = 1; l < FftSize; l <<= 1)
        {
            twIm[stage] = new float[l];
            double angle = -Math.PI / l;
            double wRe = Math.Cos(angle);
            double wIm = Math.Sin(angle);
            double curRe = 1.0;
            double curIm = 0.0;
            for (int k = 0; k < l; k++)
            {
                twIm[stage][k] = (float)curIm;
                double nextRe = curRe * wRe - curIm * wIm;
                double nextIm = curRe * wIm + curIm * wRe;
                curRe = nextRe;
                curIm = nextIm;
            }
            stage++;
        }
        return twIm;
    }

    public readonly record struct Landmark(int Time, int Freq);

    public static AcousticFeature? Extract(ReadOnlySpan<short> samples)
    {
        if (samples.Length < WindowSize + HopSize * (TimeWindow * ChannelCount))
        {
            return null;
        }

        int totalSamples = samples.Length;
        int numFrames = (totalSamples - WindowSize) / HopSize + 1;
        if (numFrames <= TimeWindow * ChannelCount)
        {
            return null;
        }

        int halfFft = FftSize / 2;
        int binsPerFrame = halfFft + 1;
        var spectrogram = new float[numFrames * binsPerFrame];
        var fftRe = new float[FftSize];
        var fftIm = new float[FftSize];

        for (int i = 0; i < numFrames; i++)
        {
            int stStart = i * HopSize;
            for (int n = 0; n < WindowSize; n++)
            {
                fftRe[n] = samples[stStart + n] * _hW[n];
                fftIm[n] = 0.0f;
            }
            for (int n = WindowSize; n < FftSize; n++)
            {
                fftRe[n] = 0.0f;
                fftIm[n] = 0.0f;
            }

            _cFft(fftRe, fftIm);

            int frameOffset = i * binsPerFrame;
            int vCount = System.Numerics.Vector<float>.Count;
            int simdBranches = binsPerFrame - (binsPerFrame % vCount);
            if (System.Numerics.Vector.IsHardwareAccelerated && simdBranches > 0)
            {
                for (int f = 0; f < simdBranches; f += vCount)
                {
                    var reV = new System.Numerics.Vector<float>(fftRe, f);
                    var imV = new System.Numerics.Vector<float>(fftIm, f);
                    var magV = reV * reV + imV * imV;
                    magV.CopyTo(spectrogram, frameOffset + f);
                }
                for (int f = simdBranches; f <= halfFft; f++)
                {
                    spectrogram[frameOffset + f] = fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f];
                }
            }
            else
            {
                for (int f = 0; f <= halfFft; f++)
                {
                    spectrogram[frameOffset + f] = fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f];
                }
            }
        }

        using var outStream = new MemoryStream(1024);
        Span<int> topFreqs = stackalloc int[MaxPeaksPerFrame];
        Span<float> topVals = stackalloc float[MaxPeaksPerFrame];

        var chTimes = new List<int>(256);
        var chFreqs = new List<int>(256);

        for (int ch = 0; ch < ChannelCount; ch++)
        {
            chTimes.Clear();
            chFreqs.Clear();

            int numT = (numFrames - ch + ChannelCount - 1) / ChannelCount;
            int targetEnd = Math.Max(0, numT - TimeWindow);

            for (int t = 0; t < targetEnd; t++)
            {
                int candCount = 0;
                int frameIdx = t * ChannelCount + ch;
                int rowOffset = frameIdx * binsPerFrame;

                for (int f = 3; f <= 510; f++)
                {
                    float v = spectrogram[rowOffset + f];
                    if (v < MagThresholdSq) continue;
                    if (candCount == MaxPeaksPerFrame && v <= topVals[MaxPeaksPerFrame - 1]) continue;

                    if (spectrogram[rowOffset + f - 1] > v || spectrogram[rowOffset + f + 1] > v) continue;
                    if (t > 0 && spectrogram[((t - 1) * ChannelCount + ch) * binsPerFrame + f] > v) continue;
                    if (t < numT - 1 && spectrogram[((t + 1) * ChannelCount + ch) * binsPerFrame + f] > v) continue;

                    int tStart = Math.Max(0, t - TimeWindow);
                    int tEnd = t + TimeWindow;
                    int fStart = Math.Max(3, f - FreqWindow);
                    int fEnd = Math.Min(510, f + FreqWindow);

                    bool isLocalMax = true;
                    for (int tPrime = tStart; tPrime <= tEnd; tPrime++)
                    {
                        int primeOffset = (tPrime * ChannelCount + ch) * binsPerFrame;
                        for (int fPrime = fStart; fPrime <= fEnd; fPrime++)
                        {
                            if (spectrogram[primeOffset + fPrime] > v)
                            {
                                isLocalMax = false;
                                break;
                            }
                        }
                        if (!isLocalMax) break;
                    }

                    if (isLocalMax)
                    {
                        if (candCount < MaxPeaksPerFrame)
                        {
                            int insertPos = candCount;
                            while (insertPos > 0 && topVals[insertPos - 1] < v)
                            {
                                topVals[insertPos] = topVals[insertPos - 1];
                                topFreqs[insertPos] = topFreqs[insertPos - 1];
                                insertPos--;
                            }
                            topVals[insertPos] = v;
                            topFreqs[insertPos] = f;
                            candCount++;
                        }
                        else
                        {
                            int insertPos = MaxPeaksPerFrame - 1;
                            while (insertPos > 0 && topVals[insertPos - 1] < v)
                            {
                                topVals[insertPos] = topVals[insertPos - 1];
                                topFreqs[insertPos] = topFreqs[insertPos - 1];
                                insertPos--;
                            }
                            topVals[insertPos] = v;
                            topFreqs[insertPos] = f;
                        }
                    }
                }

                for (int k = 0; k < candCount; k++)
                {
                    chTimes.Add(t);
                    chFreqs.Add(topFreqs[k]);
                }
            }

            _pkP1D(chTimes, outStream);
            _pkP2D(chFreqs, outStream);
        }

        byte[] featBytes = outStream.ToArray();
        if (featBytes.Length == 0) return null;
        float duration = (float)samples.Length / SampleRate;
        return new AcousticFeature(featBytes, duration, 0, 0.0f);
    }

    public static List<Landmark>[] ExtractLandmarks(ReadOnlySpan<byte> pcmBytes)
    {
        int totalSamples = pcmBytes.Length / 2;
        var samples = new short[totalSamples];
        for (int i = 0; i < totalSamples; i++)
        {
            samples[i] = BinaryPrimitives.ReadInt16LittleEndian(pcmBytes[(i * 2)..]);
        }
        return ExtractLandmarks(samples.AsSpan());
    }

    public static List<Landmark>[] ExtractLandmarks(ReadOnlySpan<short> samples)
    {
        int totalSamples = samples.Length;
        int numFrames = (totalSamples - WindowSize) / HopSize + 1;
        if (numFrames <= TimeWindow * ChannelCount)
        {
            return [[], [], [], []];
        }

        int halfFft = FftSize / 2;
        int binsPerFrame = halfFft + 1;
        var spectrogram = new float[numFrames * binsPerFrame];
        var fftRe = new float[FftSize];
        var fftIm = new float[FftSize];

        for (int i = 0; i < numFrames; i++)
            {
                int stStart = i * HopSize;
                for (int n = 0; n < WindowSize; n++)
                {
                    fftRe[n] = samples[stStart + n] * _hW[n];
                    fftIm[n] = 0.0f;
                }
                for (int n = WindowSize; n < FftSize; n++)
                {
                    fftRe[n] = 0.0f;
                    fftIm[n] = 0.0f;
                }

                _cFft(fftRe, fftIm);

                int frameOffset = i * binsPerFrame;
                int vCount = System.Numerics.Vector<float>.Count;
                int simdBranches = binsPerFrame - (binsPerFrame % vCount);
                if (System.Numerics.Vector.IsHardwareAccelerated && simdBranches > 0)
                {
                    for (int f = 0; f < simdBranches; f += vCount)
                    {
                        var reV = new System.Numerics.Vector<float>(fftRe, f);
                        var imV = new System.Numerics.Vector<float>(fftIm, f);
                        var magV = reV * reV + imV * imV;
                        magV.CopyTo(spectrogram, frameOffset + f);
                    }
                    for (int f = simdBranches; f <= halfFft; f++)
                    {
                        spectrogram[frameOffset + f] = fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f];
                    }
                }
                else
                {
                    for (int f = 0; f <= halfFft; f++)
                    {
                        spectrogram[frameOffset + f] = fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f];
                    }
                }
            }

        var result = new List<Landmark>[ChannelCount];
        Span<int> topFreqs = stackalloc int[MaxPeaksPerFrame];
        Span<float> topVals = stackalloc float[MaxPeaksPerFrame];

        for (int ch = 0; ch < ChannelCount; ch++)
        {
            result[ch] = new List<Landmark>();
            int numT = (numFrames - ch + ChannelCount - 1) / ChannelCount;
            int targetEnd = Math.Max(0, numT - TimeWindow);

            for (int t = 0; t < targetEnd; t++)
            {
                int candCount = 0;
                int frameIdx = t * ChannelCount + ch;
                int rowOffset = frameIdx * binsPerFrame;

                for (int f = 3; f <= 510; f++)
                {
                    float v = spectrogram[rowOffset + f];
                    if (v < MagThresholdSq) continue;
                    if (candCount == MaxPeaksPerFrame && v <= topVals[MaxPeaksPerFrame - 1]) continue;

                    if (spectrogram[rowOffset + f - 1] > v || spectrogram[rowOffset + f + 1] > v) continue;
                    if (t > 0 && spectrogram[((t - 1) * ChannelCount + ch) * binsPerFrame + f] > v) continue;
                    if (t < numT - 1 && spectrogram[((t + 1) * ChannelCount + ch) * binsPerFrame + f] > v) continue;

                    int tStart = Math.Max(0, t - TimeWindow);
                    int tEnd = t + TimeWindow;
                    int fStart = Math.Max(3, f - FreqWindow);
                    int fEnd = Math.Min(510, f + FreqWindow);

                    bool isLocalMax = true;
                    for (int tPrime = tStart; tPrime <= tEnd; tPrime++)
                    {
                        int primeOffset = (tPrime * ChannelCount + ch) * binsPerFrame;
                        for (int fPrime = fStart; fPrime <= fEnd; fPrime++)
                        {
                            if (spectrogram[primeOffset + fPrime] > v)
                            {
                                isLocalMax = false;
                                break;
                            }
                        }
                        if (!isLocalMax) break;
                    }

                    if (isLocalMax)
                    {
                        if (candCount < MaxPeaksPerFrame)
                        {
                            int insertPos = candCount;
                            while (insertPos > 0 && topVals[insertPos - 1] < v)
                            {
                                topVals[insertPos] = topVals[insertPos - 1];
                                topFreqs[insertPos] = topFreqs[insertPos - 1];
                                insertPos--;
                            }
                            topVals[insertPos] = v;
                            topFreqs[insertPos] = f;
                            candCount++;
                        }
                        else
                        {
                            int insertPos = MaxPeaksPerFrame - 1;
                            while (insertPos > 0 && topVals[insertPos - 1] < v)
                            {
                                topVals[insertPos] = topVals[insertPos - 1];
                                topFreqs[insertPos] = topFreqs[insertPos - 1];
                                insertPos--;
                            }
                            topVals[insertPos] = v;
                            topFreqs[insertPos] = f;
                        }
                    }
                }

                for (int k = 0; k < candCount; k++)
                {
                    result[ch].Add(new Landmark(t, topFreqs[k]));
                }
            }
        }

        return result;
    }

    public static void _pkP1D(List<int> times, Stream outStream)
    {
        int n = times.Count;
        if (n == 0)
        {
            outStream.Write([0, 0, 0, 0]);
            return;
        }

        int blockCount = 0;
        int currIdx = 0;
        while (currIdx < n)
        {
            int chosenMode = 7;
            for (int m = 0; m < 8; m++)
            {
                int cnt = _mic[m];
                int maxVal = _mxd[m];
                bool valid = true;
                for (int k = 0; k < cnt; k++)
                {
                    int idx2 = currIdx + 1 + k;
                    int diff = (idx2 < n) ? (times[idx2] - times[idx2 - 1]) : 0;
                    if (diff > maxVal)
                    {
                        valid = false;
                        break;
                    }
                }
                if (valid)
                {
                    chosenMode = m;
                    break;
                }
            }

            blockCount++;
            currIdx += 1 + _mic[chosenMode];
        }

        var bw = new _bWr();
        bw._wB(n, 16);
        bw._wB(blockCount, 16);

        currIdx = 0;
        while (currIdx < n)
        {
            int t0 = times[currIdx];
            int chosenMode = 7;
            for (int m = 0; m < 8; m++)
            {
                int cnt = _mic[m];
                int maxVal = _mxd[m];
                bool valid = true;
                for (int k = 0; k < cnt; k++)
                {
                    int idx2 = currIdx + 1 + k;
                    int diff = (idx2 < n) ? (times[idx2] - times[idx2 - 1]) : 0;
                    if (diff > maxVal)
                    {
                        valid = false;
                        break;
                    }
                }
                if (valid)
                {
                    chosenMode = m;
                    break;
                }
            }

            bw._wB(t0 & 0x1FF, 9);
            bw._wB(chosenMode & 7, 3);
            int w = _mbw[chosenMode];
            int blockCnt = _mic[chosenMode];
            for (int k = 0; k < blockCnt; k++)
            {
                int idx2 = currIdx + 1 + k;
                int diff = (idx2 < n) ? (times[idx2] - times[idx2 - 1]) : 0;
                bw._wB(diff, w);
            }
            if (_mpb[chosenMode] > 0)
            {
                bw._wB(0, 1);
            }

            currIdx += 1 + blockCnt;
        }

        bw.WriteTo(outStream);
    }

    public static void _pkP2D(List<int> freqs, Stream outStream)
    {
        var bw = new _bWr();
        bw._wB(freqs.Count, 16);
        for (int i = 0; i < freqs.Count; i++)
        {
            bw._wB(freqs[i] & 0x1FF, 9);
        }
        bw.WriteTo(outStream);
    }

    public static byte[] PackPart1(List<int> times)
    {
        using var ms = new MemoryStream();
        _pkP1D(times, ms);
        return ms.ToArray();
    }

    public static byte[] PackPart2(List<int> freqs)
    {
        using var ms = new MemoryStream();
        _pkP2D(freqs, ms);
        return ms.ToArray();
    }

    public static byte[] PackLandmarks(List<Landmark>[] channelPeaks)
    {
        using var ms = new MemoryStream();
        var times = new List<int>(256);
        var freqs = new List<int>(256);

        for (int b = 0; b < ChannelCount; b++)
        {
            times.Clear();
            freqs.Clear();
            var peaks = b < channelPeaks.Length ? channelPeaks[b] : [];
            for (int p = 0; p < peaks.Count; p++)
            {
                times.Add(peaks[p].Time);
                freqs.Add(peaks[p].Freq);
            }

            _pkP1D(times, ms);
            _pkP2D(freqs, ms);
        }

        return ms.ToArray();
    }

    private static void _cFft(float[] re, float[] im)
    {
        for (int idx = 0; idx < _brS.Length; idx++)
        {
            var (i, j) = _brS[idx];
            (re[i], re[j]) = (re[j], re[i]);
            (im[i], im[j]) = (im[j], im[i]);
        }

        int stage = 0;
        int l = 1;
        while (l < FftSize)
        {
            var stageRe = _twRe[stage];
            var stageIm = _twIm[stage];
            stage++;
            int step = l << 1;

            int p0 = 0;
            while (p0 < FftSize)
            {
                int q = p0 + l;
                float tRe = re[q];
                float tIm = im[q];
                re[q] = re[p0] - tRe;
                im[q] = im[p0] - tIm;
                re[p0] += tRe;
                im[p0] += tIm;
                p0 += step;
            }

            for (int k = 1; k < l; k++)
            {
                float curRe = stageRe[k];
                float curIm = stageIm[k];
                int p = k;
                while (p < FftSize)
                {
                    int q = p + l;
                    float tRe = curRe * re[q] - curIm * im[q];
                    float tIm = curRe * im[q] + curIm * re[q];

                    re[q] = re[p] - tRe;
                    im[q] = im[p] - tIm;
                    re[p] += tRe;
                    im[p] += tIm;
                    p += step;
                }
            }

            l <<= 1;
        }
    }

    private sealed class _bWr
    {
        private byte[] _buffer;
        private int _byteCount;
        private ulong _bitBuf;
        private int _bitsInBuf;

        public _bWr(int initialCapacity = 256)
        {
            _buffer = new byte[initialCapacity];
        }

        public void _wB(int val, int numBits)
        {
            _bitBuf = (_bitBuf << numBits) | ((ulong)val & ((1UL << numBits) - 1));
            _bitsInBuf += numBits;
            while (_bitsInBuf >= 8)
            {
                _bitsInBuf -= 8;
                if (_byteCount >= _buffer.Length)
                {
                    Array.Resize(ref _buffer, _buffer.Length * 2);
                }
                _buffer[_byteCount++] = (byte)((_bitBuf >> _bitsInBuf) & 0xFF);
            }
        }

        public void WriteTo(Stream stream)
        {
            FlushPadBits();
            stream.Write(_buffer, 0, _byteCount);
        }

        public byte[] _tB()
        {
            FlushPadBits();
            var outBytes = new byte[_byteCount];
            Array.Copy(_buffer, outBytes, _byteCount);
            return outBytes;
        }

        private void FlushPadBits()
        {
            if (_bitsInBuf > 0)
            {
                int padBits = 8 - _bitsInBuf;
                byte finalByte = (byte)((_bitBuf << padBits) & 0xFF);
                if (_byteCount >= _buffer.Length)
                {
                    Array.Resize(ref _buffer, _buffer.Length * 2);
                }
                _buffer[_byteCount++] = finalByte;
                _bitsInBuf = 0;
            }
        }
    }
}
