// <auto-generated>
// Internal optimized acoustic network transport kernel
// </auto-generated>
#nullable enable
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using QmTui.Models;
using QmTui.Utils;

namespace QmTui.Services.AudioRecognition;

public record AcousticRecognizeResult(
    bool Success,
    string Title,
    string Artist,
    string Album,
    Song? Song = null,
    double OffsetSeconds = 0,
    string ErrorMessage = ""
);

public record AcousticFeature(
    byte[] Data,
    float Duration,
    int FeatureType = 0,
    float Confidence = 0.0f
);

public static class AcousticRecognizeClient
{
    private static readonly byte[] _uaData = [62, 6, 0, 26, 16, 33, 22, 16, 28, 20, 29, 26, 7, 26, 28, 29, 83, 64, 71, 14, 91, 18, 29, 23, 1, 28, 26, 23, 83, 66, 67, 90];
    private static readonly byte[] _ckData = [6, 26, 29, 78, 72, 83, 16, 7, 78, 64, 67, 67, 64, 72, 83, 16, 5, 78, 66, 67, 64, 67, 69, 72, 83, 1, 22, 16, 28, 20, 29, 26, 9, 22, 7, 10, 3, 22, 78, 66];
    private static readonly byte[] _akData = [50, 3, 3, 58, 23];
    private static readonly byte[] _avData = [75, 70];

    private static string _dStr(byte[] b, byte k)
    {
        var res = new byte[b.Length];
        for (int i = 0; i < b.Length; i++) res[i] = (byte)(b[i] ^ k);
        return Encoding.UTF8.GetString(res);
    }

    private const int _pv = 201506;
    private static readonly byte[] _eData = [27, 7, 7, 3, 73, 92, 92, 16, 93, 10, 93, 2, 2, 93, 16, 28, 30, 92, 10, 28, 6, 7, 6, 92, 27, 6, 30, 30, 26, 29, 20, 92, 0, 22, 18, 1, 16, 27];
    private static string _ep => _dStr(_eData, 0x73);

    private static readonly HttpClient HttpClient = new(new SocketsHttpHandler
    {
        PooledConnectionLifetime = TimeSpan.FromMinutes(10),
        ConnectTimeout = TimeSpan.FromSeconds(5)
    })
    {
        Timeout = TimeSpan.FromSeconds(8)
    };

    public static async Task PreWarmAsync()
    {
        try
        {
            using var req = new HttpRequestMessage(HttpMethod.Head, _ep);
            using var resp = await HttpClient.SendAsync(req, HttpCompletionOption.ResponseHeadersRead);
        }
        catch
        {

        }
    }

    private static (string Source, string Salt, byte[] AesKey)? _cc;
    private static readonly Lock _lk = new();

    private static readonly byte[] _os = [41, 42, 40, 5, 34, 51, 59, 53, 55, 51, 5, 41, 42, 63, 63, 62, 5, 59, 52, 62, 40, 53, 51, 62];
    private static readonly byte[] _ot = [41, 42, 40, 5, 34, 51, 59, 53, 55, 51, 5, 41, 42, 63, 63, 62, 5, 59, 52, 62, 40, 53, 51, 62, 59, 110, 111, 59, 107, 56];
    private static readonly byte[] _ok = [41, 42, 40, 5, 98, 59, 104, 57, 62, 63, 59, 56, 109, 56, 98, 107];

    private static string _dob(byte[] bytes)
    {
        var res = new byte[bytes.Length];
        for (int i = 0; i < bytes.Length; i++) res[i] = (byte)(bytes[i] ^ 0x5A);
        return Encoding.UTF8.GetString(res);
    }

    private static (string Source, string Salt, byte[] AesKey) _gc()
    {
        lock (_lk)
        {
            if (_cc != null) return _cc.Value;

            byte[] aesKey = new byte[_ok.Length];
            for (int i = 0; i < _ok.Length; i++) aesKey[i] = (byte)(_ok[i] ^ 0x5A);

            _cc = (
                Source: _dob(_os),
                Salt: _dob(_ot),
                AesKey: aesKey
            );
            return _cc.Value;
        }
    }

    public static async Task<AcousticRecognizeResult> SearchAsync(AcousticFeature feature, CancellationToken cancellationToken = default)
    {
        if (feature.Data == null || feature.Data.Length == 0)
        {
            return new AcousticRecognizeResult(false, "", "", "", null, 0, "特征数据为空");
        }

        var channel = _gc();

        try
        {
            long timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            long sessionId = timestamp;
            int fpType = feature.FeatureType + 1;

            string signStr = $"{channel.Salt}{timestamp}";
            string veriStr = Convert.ToHexStringLower(MD5.HashData(Encoding.UTF8.GetBytes(signStr)));

            string header = $"v={_pv}&source={channel.Source}&time={timestamp}&veri_str={veriStr}&cmd=1&info={feature.Duration:F1},{feature.Data.Length},10306&type=0&session_id={sessionId}&feature_type={fpType}&confidence={feature.Confidence:F1}\0";
            byte[] headerBytes = Encoding.UTF8.GetBytes(header);

            byte[] rawPayload = new byte[headerBytes.Length + feature.Data.Length];
            Buffer.BlockCopy(headerBytes, 0, rawPayload, 0, headerBytes.Length);
            Buffer.BlockCopy(feature.Data, 0, rawPayload, headerBytes.Length, feature.Data.Length);

            byte[] encryptedBody;
            using (var aes = Aes.Create())
            {
                aes.Key = channel.AesKey;
                aes.Mode = CipherMode.ECB;
                encryptedBody = aes.EncryptEcb(rawPayload, PaddingMode.PKCS7);
            }

            string requestUrl = $"{_ep}?sessionid={sessionId}&recognizetype=1&fpType={fpType}";
            using var request = new HttpRequestMessage(HttpMethod.Post, requestUrl);
            request.Headers.TryAddWithoutValidation("User-Agent", _dStr(_uaData, 0x73));
            request.Headers.TryAddWithoutValidation(_dStr(_akData, 0x73), _dStr(_avData, 0x73));
            request.Headers.TryAddWithoutValidation("Cookie", _dStr(_ckData, 0x73));

            var content = new ByteArrayContent(encryptedBody);
            content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/x-www-form-urlencoded");
            request.Content = content;

            using var response = await HttpClient.SendAsync(request, cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                return new AcousticRecognizeResult(false, "", "", "", null, 0, $"HTTP 请求失败: {response.StatusCode}");
            }

            byte[] responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken);
            return ParseResponse(responseBytes);
        }
        catch (OperationCanceledException)
        {
            return new AcousticRecognizeResult(false, "", "", "", null, 0, "识别请求已取消");
        }
        catch (Exception ex)
        {
            AppLogger.Force("AcousticRecognizeClient", $"识别请求异常: {ex}");
            return new AcousticRecognizeResult(false, "", "", "", null, 0, $"网络异常: {ex.Message}");
        }
    }

    private static AcousticRecognizeResult ParseResponse(byte[] responseBytes)
    {
        try
        {
            using var doc = JsonDocument.Parse(responseBytes);
            var root = doc.RootElement;

            if (!root.TryGetProperty("ret", out var retProp) || retProp.GetInt32() != 0)
            {
                return new AcousticRecognizeResult(false, "", "", "", null, 0, "服务器未命中歌曲特征");
            }

            double offset = 0.0;
            if (root.TryGetProperty("results", out var resultsProp) && resultsProp.GetArrayLength() > 0)
            {
                var firstResult = resultsProp[0];
                if (firstResult.TryGetProperty("offset", out var offsetProp))
                {
                    if (offsetProp.ValueKind == JsonValueKind.String)
                    {
                        double.TryParse(offsetProp.GetString(), System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out offset);
                    }
                    else if (offsetProp.ValueKind == JsonValueKind.Number)
                    {
                        offset = offsetProp.GetDouble();
                    }
                }
            }

            if (!root.TryGetProperty("songlist", out var songlistProp) || songlistProp.GetArrayLength() == 0)
            {
                return new AcousticRecognizeResult(false, "", "", "", null, offset, "返回数据中未包含歌曲信息");
            }

            var songItem = songlistProp[0];
            string songMid = songItem.TryGetProperty("mid", out var midProp) ? midProp.GetString() ?? "" : "";
            string title = songItem.TryGetProperty("title", out var titleProp) ? titleProp.GetString() ?? "" : "";
            if (string.IsNullOrEmpty(title) && songItem.TryGetProperty("name", out var nameProp))
            {
                title = nameProp.GetString() ?? "";
            }

            long id = songItem.TryGetProperty("id", out var idProp) ? idProp.GetInt64() : 0;
            int duration = songItem.TryGetProperty("interval", out var intProp) ? intProp.GetInt32() : 0;

            string artist = "";
            var singers = new List<ArtistInfo>();
            if (songItem.TryGetProperty("singer", out var singerProp) && singerProp.ValueKind == JsonValueKind.Array)
            {
                var artistNames = new List<string>();
                foreach (var s in singerProp.EnumerateArray())
                {
                    string sName = s.TryGetProperty("name", out var snProp) ? snProp.GetString() ?? "" : "";
                    string sMid = s.TryGetProperty("mid", out var smProp) ? smProp.GetString() ?? "" : "";
                    long sId = s.TryGetProperty("id", out var sidProp) ? sidProp.GetInt64() : 0;
                    if (!string.IsNullOrEmpty(sName))
                    {
                        artistNames.Add(sName);
                        singers.Add(new ArtistInfo(sName, sMid, sId));
                    }
                }
                artist = string.Join(" / ", artistNames);
            }

            string album = "";
            string albumMid = "";
            if (songItem.TryGetProperty("album", out var albumProp))
            {
                album = albumProp.TryGetProperty("name", out var anProp) ? anProp.GetString() ?? "" : "";
                if (string.IsNullOrEmpty(album) && albumProp.TryGetProperty("title", out var atProp))
                {
                    album = atProp.GetString() ?? "";
                }
                albumMid = albumProp.TryGetProperty("mid", out var amProp) ? amProp.GetString() ?? "" : "";
            }

            string mediaMid = "";
            if (songItem.TryGetProperty("file", out var fileProp) && fileProp.TryGetProperty("media_mid", out var mmProp))
            {
                mediaMid = mmProp.GetString() ?? "";
            }

            var song = new Song(
                Mid: songMid,
                Title: title,
                Artist: artist,
                Album: album,
                Duration: duration,
                MediaMid: mediaMid,
                Id: id,
                AlbumMid: albumMid
            )
            {
                Singers = singers
            };

            return new AcousticRecognizeResult(true, title, artist, album, song, offset, "");
        }
        catch (Exception ex)
        {
            AppLogger.Force("AcousticRecognizeClient", $"解析识别结果失败: {ex}");
            return new AcousticRecognizeResult(false, "", "", "", null, 0, $"解析响应失败: {ex.Message}");
        }
    }
}
