// <auto-generated>
// High performance acoustic stream transformation pipeline
// </auto-generated>
#nullable enable
using System.Buffers.Binary;
using QmTui.Utils;

namespace QmTui.Services.AudioRecognition;

public static class AcousticFingerprintExtractor
{
    public const int SampleRate = 8000;
    public const int WindowSize = 1024;
    public const int HopSize = 128;
    public const int FftSize = 1024;
    public const int ChannelCount = 4;
    public const int TimeWindow = 5;
    public const int FreqWindow = 20;
    public const int MaxPeaksPerFrame = 5;
    public const float MagThreshold = 20000.0f;

    private static readonly float[] _hW = _inHw();
    private static readonly (int i, int j)[] _brS = _inBrs();
    private static readonly (float Re, float Im)[][] _tw = _inTw();

    private static readonly int[] _mbw = [1, 2, 3, 4, 5, 6, 7, 9];
    private static readonly int[] _mic = [36, 18, 12, 9, 7, 6, 5, 4];
    private static readonly int[] _mpb = [0, 0, 0, 0, 1, 0, 1, 0];
    private static readonly int[] _mxd = [1, 3, 4, 15, 31, 63, 127, 511];

    private static float[] _inHw()
    {
        var win = new float[WindowSize];
        for (int n = 0; n < WindowSize; n++)
        {
            win[n] = (float)(0.54 - 0.46 * Math.Cos(2.0 * Math.PI * n / (WindowSize - 1)));
        }
        return win;
    }

    private static (int, int)[] _inBrs()
    {
        var swaps = new List<(int, int)>();
        int j = 0;
        for (int i = 0; i < FftSize - 1; i++)
        {
            if (i < j)
            {
                swaps.Add((i, j));
            }
            int k = FftSize >> 1;
            while (k <= j)
            {
                j -= k;
                k >>= 1;
            }
            j += k;
        }
        return swaps.ToArray();
    }

    private static (float Re, float Im)[][] _inTw()
    {
        var tw = new (float Re, float Im)[10][];
        int stage = 0;
        for (int l = 1; l < FftSize; l <<= 1)
        {
            tw[stage] = new (float, float)[l];
            double angle = -Math.PI / l;
            double wRe = Math.Cos(angle);
            double wIm = Math.Sin(angle);
            double curRe = 1.0;
            double curIm = 0.0;
            for (int k = 0; k < l; k++)
            {
                tw[stage][k] = ((float)curRe, (float)curIm);
                double nextRe = curRe * wRe - curIm * wIm;
                double nextIm = curRe * wIm + curIm * wRe;
                curRe = nextRe;
                curIm = nextIm;
            }
            stage++;
        }
        return tw;
    }

    public readonly record struct Landmark(int Time, int Freq);

    public static AcousticFeature? Extract(ReadOnlySpan<short> samples)
    {
        if (samples.Length < WindowSize + HopSize * (TimeWindow * ChannelCount))
        {
            return null;
        }

        var landmarks = ExtractLandmarks(samples);
        byte[] featBytes = PackLandmarks(landmarks);
        if (featBytes.Length == 0)
        {
            return null;
        }

        float duration = (float)samples.Length / SampleRate;
        return new AcousticFeature(featBytes, duration, 0, 0.0f);
    }

    public static List<Landmark>[] ExtractLandmarks(ReadOnlySpan<byte> pcmBytes)
    {
        int totalSamples = pcmBytes.Length / 2;
        var samples = new short[totalSamples];
        for (int i = 0; i < totalSamples; i++)
        {
            samples[i] = BinaryPrimitives.ReadInt16LittleEndian(pcmBytes[(i * 2)..]);
        }
        return ExtractLandmarks(samples.AsSpan());
    }

    public static List<Landmark>[] ExtractLandmarks(ReadOnlySpan<short> samples)
    {
        int totalSamples = samples.Length;
        int numFrames = (totalSamples - WindowSize) / HopSize + 1;
        if (numFrames <= TimeWindow * ChannelCount)
        {
            return [[], [], [], []];
        }

        var spectrogram = new float[numFrames][];
        var fftRe = new float[FftSize];
        var fftIm = new float[FftSize];
        int vCount = System.Numerics.Vector<float>.Count;
        int halfFft = FftSize / 2;
        int simdBranches = halfFft - (halfFft % vCount);

        for (int i = 0; i < numFrames; i++)
        {
            int stStart = i * HopSize;
            for (int n = 0; n < WindowSize; n++)
            {
                fftRe[n] = samples[stStart + n] * _hW[n];
                fftIm[n] = 0.0f;
            }

            _cFft(fftRe, fftIm);

            var mag = new float[halfFft + 1];
            if (System.Numerics.Vector.IsHardwareAccelerated && simdBranches > 0)
            {
                for (int f = 0; f < simdBranches; f += vCount)
                {
                    var reV = new System.Numerics.Vector<float>(fftRe, f);
                    var imV = new System.Numerics.Vector<float>(fftIm, f);
                    var magV = System.Numerics.Vector.SquareRoot(reV * reV + imV * imV);
                    magV.CopyTo(mag, f);
                }
                for (int f = simdBranches; f <= halfFft; f++)
                {
                    mag[f] = MathF.Sqrt(fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f]);
                }
            }
            else
            {
                for (int f = 0; f <= halfFft; f++)
                {
                    mag[f] = MathF.Sqrt(fftRe[f] * fftRe[f] + fftIm[f] * fftIm[f]);
                }
            }
            spectrogram[i] = mag;
        }

        var channelSpecs = new List<float[]>[ChannelCount];
        for (int ch = 0; ch < ChannelCount; ch++)
        {
            channelSpecs[ch] = new List<float[]>(numFrames / ChannelCount + 1);
        }

        for (int i = 0; i < numFrames; i++)
        {
            channelSpecs[i % ChannelCount].Add(spectrogram[i]);
        }

        var result = new List<Landmark>[ChannelCount];

        var cands = new List<(int f, float val)>(64);
        for (int ch = 0; ch < ChannelCount; ch++)
        {
            var spec = channelSpecs[ch];
            int numT = spec.Count;
            result[ch] = new List<Landmark>();

            int targetEnd = Math.Max(0, numT - TimeWindow);
            for (int t = 0; t < targetEnd; t++)
            {
                cands.Clear();
                for (int f = 3; f <= 510; f++)
                {
                    float val = spec[t][f];
                    if (val < MagThreshold) continue;

                    int tStart = Math.Max(0, t - TimeWindow);
                    int tEnd = t + TimeWindow;
                    int fStart = Math.Max(3, f - FreqWindow);
                    int fEnd = Math.Min(510, f + FreqWindow);

                    bool isLocalMax = true;
                    for (int tPrime = tStart; tPrime <= tEnd && isLocalMax; tPrime++)
                    {
                        var row = spec[tPrime];
                        for (int fPrime = fStart; fPrime <= fEnd; fPrime++)
                        {
                            if (row[fPrime] > val)
                            {
                                isLocalMax = false;
                                break;
                            }
                        }
                    }

                    if (isLocalMax)
                    {
                        cands.Add((f, val));
                    }
                }

                cands.Sort((a, b) => b.val.CompareTo(a.val));
                int take = Math.Min(MaxPeaksPerFrame, cands.Count);
                for (int k = 0; k < take; k++)
                {
                    result[ch].Add(new Landmark(t, cands[k].f));
                }
            }
        }

        return result;
    }

    public static byte[] PackPart1(List<int> times)
    {
        int n = times.Count;
        if (n == 0) return [0, 0, 0, 0];

        var blocks = new List<(int t0, int mode, List<int> diffs)>();
        int currIdx = 0;
        while (currIdx < n)
        {
            int t0 = times[currIdx];
            int chosenMode = 7;
            for (int m = 0; m < 8; m++)
            {
                int cnt = _mic[m];
                int maxVal = _mxd[m];
                bool valid = true;
                for (int k = 0; k < cnt; k++)
                {
                    int idx2 = currIdx + 1 + k;
                    int diff = (idx2 < n) ? (times[idx2] - times[idx2 - 1]) : 0;
                    if (diff > maxVal)
                    {
                        valid = false;
                        break;
                    }
                }
                if (valid)
                {
                    chosenMode = m;
                    break;
                }
            }

            int blockCnt = _mic[chosenMode];
            var blockDiffs = new List<int>(blockCnt);
            for (int k = 0; k < blockCnt; k++)
            {
                int idx2 = currIdx + 1 + k;
                int diff = (idx2 < n) ? (times[idx2] - times[idx2 - 1]) : 0;
                blockDiffs.Add(diff);
            }

            blocks.Add((t0, chosenMode, blockDiffs));
            currIdx += 1 + blockCnt;
        }

        var bw = new _bWr();
        bw._wB(n, 16);
        bw._wB(blocks.Count, 16);

        foreach (var (t0, mode, diffs) in blocks)
        {
            bw._wB(t0 & 0x1FF, 9);
            bw._wB(mode & 7, 3);
            int w = _mbw[mode];
            foreach (var d in diffs)
            {
                bw._wB(d, w);
            }
            if (_mpb[mode] > 0)
            {
                bw._wB(0, 1);
            }
        }

        return bw._tB();
    }

    public static byte[] PackPart2(List<int> freqs)
    {
        var bw = new _bWr();
        bw._wB(freqs.Count, 16);
        foreach (var f in freqs)
        {
            bw._wB(f & 0x1FF, 9);
        }
        return bw._tB();
    }

    public static byte[] PackLandmarks(List<Landmark>[] channelPeaks)
    {
        using var ms = new MemoryStream();

        for (int b = 0; b < ChannelCount; b++)
        {
            var peaks = b < channelPeaks.Length ? channelPeaks[b] : [];
            var times = new List<int>(peaks.Count);
            var freqs = new List<int>(peaks.Count);
            for (int p = 0; p < peaks.Count; p++)
            {
                times.Add(peaks[p].Time);
                freqs.Add(peaks[p].Freq);
            }

            var p1 = PackPart1(times);
            var p2 = PackPart2(freqs);

            ms.Write(p1);
            ms.Write(p2);
        }

        return ms.ToArray();
    }

    private static void _cFft(float[] re, float[] im)
    {
        for (int idx = 0; idx < _brS.Length; idx++)
        {
            var (i, j) = _brS[idx];
            (re[i], re[j]) = (re[j], re[i]);
            (im[i], im[j]) = (im[j], im[i]);
        }

        int stage = 0;
        for (int l = 1; l < FftSize; l <<= 1)
        {
            var stageTwiddles = _tw[stage++];
            int step = l << 1;
            for (int m = 0; m < FftSize; m += step)
            {
                for (int k = 0; k < l; k++)
                {
                    int p = m + k;
                    int q = p + l;

                    var (curRe, curIm) = stageTwiddles[k];
                    float tRe = curRe * re[q] - curIm * im[q];
                    float tIm = curRe * im[q] + curIm * re[q];

                    re[q] = re[p] - tRe;
                    im[q] = im[p] - tIm;
                    re[p] += tRe;
                    im[p] += tIm;
                }
            }
        }
    }

    private sealed class _bWr
    {
        private byte[] _buffer = new byte[256];
        private int _bitCount;

        public void _wB(int val, int numBits)
        {
            for (int i = numBits - 1; i >= 0; i--)
            {
                int bit = (val >> i) & 1;
                int byteIdx = _bitCount >> 3;
                int bitPos = 7 - (_bitCount & 7);

                if (byteIdx >= _buffer.Length)
                {
                    Array.Resize(ref _buffer, _buffer.Length * 2);
                }

                if (bit != 0)
                {
                    _buffer[byteIdx] |= (byte)(1 << bitPos);
                }

                _bitCount++;
            }
        }

        public byte[] _tB()
        {
            int totalBytes = (_bitCount + 7) >> 3;
            var outBytes = new byte[totalBytes];
            Array.Copy(_buffer, outBytes, totalBytes);
            return outBytes;
        }
    }
}
