const unlisten = () => {};
export const getCurrentWindow = () => ({
  label: 'main',
  metadata: async () => ({ width: 1280, height: 860, minWidth: 320, minHeight: 240, maximized: false, fullscreen: false }),
  innerSize: async () => ({ width: window.innerWidth, height: window.innerHeight }),
  outerSize: async () => ({ width: window.innerWidth, height: window.innerHeight }),
  scaleFactor: async () => window.devicePixelRatio || 1,
  isMaximized: async () => false,
  isFullscreen: async () => false,
  isFocused: async () => true,
  setTitle: async () => {},
  setFullscreen: async () => {},
  show: async () => {},
  hide: async () => {},
  close: async () => {},
  minimize: async () => {},
  toggleMaximize: async () => {},
  startDragging: async () => {},
  listen: async () => unlisten,
  once: async () => unlisten,
  onCloseRequested: async () => unlisten,
  onResized: async () => unlisten,
  onFocusChanged: async () => unlisten,
  setTheme: async () => {},
  theme: async () => 'dark',
  setEffects: async () => {},
  onThemeChanged: async () => unlisten,
  setDecorations: async () => {},
  setShadow: async () => {},
  setResizable: async () => {},
  setMinSize: async () => {},
  setSize: async () => {},
  setPosition: async () => {},
  center: async () => {},
  setAlwaysOnTop: async () => {},
  setIgnoreCursorEvents: async () => {},
  setSkipTaskbar: async () => {},
});
